Import('env prefix')

lib_name = 'numlib_optimization'

headers = (
	'optimization_error_codes.h',
	'Minimum1D.h',
	'MinimumND.h',
	'CostFunctionND.h',
	'LineRestriction.h',
	'BracketFinder.h',
	'GoldenSection.h',
	'QuadraticInterp.h',
	'OptimizerBGQ.h',
	'OptimizerCG.h',
	'Particle.h',
	'OptimizerPSO.h',
	'StretchingOperator.h'
)

env.Install(prefix+'/include/numlib/optimization', headers)
