Import('env prefix')

lib_name = 'numlib_linalg'

headers = (
	'Vector.h',
	'Vector-inl.h',
	'VectorExpressions.h',
	'TriMatrix.h',
	'TriMatrix-inl.h',
	'TriMatrixExpressions.h',
	'HessMatrix.h',
	'HessMatrix-inl.h',
	'HessMatrixExpressions.h',
	'SquareMatrix.h',
	'SquareMatrix-inl.h',
	'SquareMatrixExpressions.h',
	'lapack_wrapper.h'
)

env.Install(prefix+'/include/numlib/linalg', headers)
