Import('env prefix')
lib_name = 'numlib_integration'

src = (
	'Quadrature.cpp',
)

headers = (
	'Quadrature.h',
	'QuadRule.h',
)

lib = env.StaticLibrary(lib_name, src)

env.Install(prefix+'/lib', lib)
env.Install(prefix+'/include/numlib/integration', headers)
