Import('env prefix')

lib_name = 'numlib_solvers'

headers = (
	'Arnoldi.h',
	'GMRES.h',
	'GalerkinProjection.h',
	'GMRESProjection.h',
	'Krylov.h',
	'KrylovSpaceAO.h',
	'GateauxFD.h',
	'NewtonKrylov.h',
	'NewtonArnoldi.h',
	'NewtonGMRES.h',
	'PseudoTransientOperator.h'
)

env.Install(prefix+'include/numlib/solvers', headers)
